### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by jsiems** [KeystoneIT/qi#4]
I just had a few questions about our workflow for this project. 

Are we going to have a Dev branch we should be merging our pull requests into? Or, are we treating 2.0 like the Dev branch? Or, are we going to have a branch specific for 2.0 called Dev2.0 or something like that? 

I am just wondering because I do not know what branch I should have in my pull request when I make one.

**Comment by s1037989** [comment]
It doesn't matter what it's called.  The workflow process is the same as with Ama.  At one point we had agreed on calling it qi2.0, but Dev, or dev, or dev2.0, or anything would be fine...  Dev would be just fine for the sake of consistency between projects.
